feature: added cache to handle jwks and changed log level
pagopa/pn-auth-fleet pull request #153
Opened 2023-07-18 09:36 UTC by empassaro

2023-07-18 18:23 UTC, MTurraPpa reviewed
Le modifiche vanno riportate anche in tokenExchange

2023-07-19 07:06 UTC, fdammassa requested changes

2023-07-19 07:06 UTC, fdammassa commented on apikeyAuthorizerV2/src/app/retrieverPdndJwks.js
> +      const response = await axios.get(jwksendpoint, { timeout: 5000 });
@empassaro perché è stato aumentato il timeout a 5 secondi?

2023-07-19 07:06 UTC, fdammassa commented on apikeyAuthorizerV2/src/app/jwksCache.js
> +const TWO_HOURS_IN_MILLISECONDS = 7200000;
@MTurraPpa è nella descrizione del task https://pagopa.atlassian.net/browse/PN-7191

2023-07-19 17:50 UTC, MTurraPpa approved these changes

2023-07-20 07:25 UTC, fdammassa requested changes

2023-07-20 07:25 UTC, fdammassa commented on tokenExchange/src/app/validation.js
> +              console.error("Validation error ", err);
@empassaro qui il log dovrebbe essere a warn per consistenza rispetto al resto

2023-07-20 07:34 UTC, fdammassa approved these changes

2023-07-20 10:15 UTC, fdammassa approved these changes

2023-07-20 12:51 UTC, merged