PN-1365: fix cx_id for PF
pagopa/pn-auth-fleet pull request #29
Opened 2022-05-05 09:43 UTC by masciale89

2022-05-05 12:38 UTC, MTurraPpa requested changes
Non vedo il test collegato a questa modifica

2022-05-05 16:06 UTC, MTurraPpa requested changes

2022-05-06 08:13 UTC, masciale89 commented on jwtAuthorizer/src/test/index.test.js
> +      console.debug('the result is ', result);
ok. Ho aggiunto la verifica al test precedente... questo era stato inserito per verificare l'utilizzo della cache

2022-05-06 08:18 UTC, MTurraPpa approved these changes

2022-05-06 08:19 UTC, merged