feature/PN-1367
pagopa/pn-auth-fleet pull request #35
Opened 2022-07-19 07:34 UTC by cFiorilloMediatica

2022-07-19 07:40 UTC, MTurraPpa requested changes
I log dovrebbero assomigliare a quelli del Backend:
```json
{
    "message": "[AUD_NT_SEARCH_RCP] SUCCESS - OK",
    "logger_name": "it.pagopa.pn.commons.log.PnAuditLog",
    "thread_name": "reactor-http-epoll-4",
    "level": "INFO",
    "level_value": 20000,
    "uid": "37654561-446a-4c88-b328-6699a8322b33",
    "trace_id": "Self=1-62d6081d-629e663a76e576260d15fb4d;Root=1-62d6081d-6b9286af1ac543cf0618efe9;Parent=1ca53299afdaff3c;Sampled=1",
    "aud_type": "AUD_NT_SEARCH_RCP",
    "cx_type": "PF",
    "cx_id": "PF-37654561-446a-4c88-b328-6699a8322b33",
    "aud_orig": "bb29cf99-047b-4b87-a6d0-88fb53225918",
    "tags": [
        "AUDIT5Y"
    ]
```

2022-07-20 10:57 UTC, MTurraPpa requested changes
Come faccio a capire qual'è l'utente che ha fatto login?
Servono i dati:
- uid
- cx_id
- cx_type

2022-07-20 14:37 UTC, MTurraPpa requested changes

2022-07-20 14:37 UTC, MTurraPpa commented on tokenExchange/src/test/audiglog.test.js
> +
Ma cosa viene controllato nel test?

2022-07-20 14:49 UTC, cFiorilloMediatica commented on tokenExchange/src/test/audiglog.test.js
> +
Ho inserito questo test per valutare la corretta formattazione del messaggio di log

2022-07-21 09:52 UTC, MTurraPpa approved these changes

2022-07-21 09:52 UTC, merged