token id in audit logs #pn-2357
pagopa/pn-auth-fleet pull request #55
Opened 2022-10-12 13:11 UTC by AndreaCimini90

2022-10-12 13:48 UTC, MTurraPpa requested changes
Andrea gli audit log non devono essere aggiunti c'era già quello di login e deve essere uno solo. Va solo aggiunta la stampa del jti in un campo json a parte e nel message

2022-10-12 13:48 UTC, MTurraPpa commented on jwtAuthorizer/src/app/eventHandler.js
> +                auditLog(`Input token ID: ${decodedToken.jti}`, 'AUD_ACC_LOGIN', event?.headers?.origin, 'OK').info('info');
Audit Log di login va solo sulla token exchange. Qua basta un log normale

2022-10-12 14:19 UTC, MTurraPpa requested changes

2022-10-12 14:19 UTC, MTurraPpa commented on tokenExchange/src/app/eventHandler.js
> +                        auditLog(`Generated token ID: ${decodedToken.jti}`, 'AUD_ACC_LOGIN', eventOrigin, 'OK').info('info');
Vogliamo aggiungere l'info al log sopra

2022-10-12 14:19 UTC, MTurraPpa commented on tokenExchange/src/app/eventHandler.js
> +                        auditLog(`Input token ID: ${decodedToken.jti}`, 'AUD_ACC_LOGIN', eventOrigin, 'OK').info('info');
Perché un altro log di LOGIN? dopo sembra che abbia fatto due login.

2022-10-12 15:18 UTC, AndreaCimini90 commented on jwtAuthorizer/src/app/eventHandler.js
> +                auditLog(`Input token ID: ${decodedToken.jti}`, 'AUD_ACC_LOGIN', event?.headers?.origin, 'OK').info('info');
Rimosso auditLog

2022-10-12 15:18 UTC, AndreaCimini90 commented on tokenExchange/src/app/eventHandler.js
> +                        auditLog(`Generated token ID: ${decodedToken.jti}`, 'AUD_ACC_LOGIN', eventOrigin, 'OK').info('info');
Fatto

2022-10-13 07:05 UTC, MTurraPpa approved these changes

2022-10-13 09:02 UTC, merged