Feature/nttdata apikey authorizer
pagopa/pn-auth-fleet pull request #66
Opened 2022-11-18 12:28 UTC by MTurraPpa

2022-11-21 10:23 UTC, fdammassa requested changes
Eliminare le stampe delle Api Key (anche se passate come parametri a messaggi delle exceptions.

2022-11-21 10:23 UTC, fdammassa commented on apikeyAuthorizerV2/src/app/eventHandler.js
> +        console.log("AWS ApiKey Found -> ", aggregateDynamo.AWSApiKey);
Eliminare, ovunque presenti, le stampe delle Api Key

2022-11-22 13:42 UTC, empassaro commented on apikeyAuthorizerV2/src/app/eventHandler.js
> +        console.log("AWS ApiKey Found -> ", aggregateDynamo.AWSApiKey);
@MTurraPpa Ciao Marco, ho aggiunto una funzione per anonimizzare il dato nella modalità richiesta e pushato.

2022-11-25 10:28 UTC, fdammassa approved these changes

2022-11-25 10:29 UTC, merged